//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger_Industry_Standard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HungerEntities : DbContext
    {
        public HungerEntities()
            : base("name=HungerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblLog> tblLogs { get; set; }
        public virtual DbSet<tblNgo> tblNgoes { get; set; }
        public virtual DbSet<TblRestrurantHeader> TblRestrurantHeaders { get; set; }
        public virtual DbSet<TblRestrurantRow> TblRestrurantRows { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    }
}
