//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger_Industry_Standard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRestrurantRow
    {
        public long intRowId { get; set; }
        public string strFood { get; set; }
        public string StrFoodType { get; set; }
        public long intRestrurantId { get; set; }
        public Nullable<long> intEmployeeId { get; set; }
        public Nullable<bool> IsCollectReqest { get; set; }
        public Nullable<System.DateTime> DteCollectionTimeLeft { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
