//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger_Industry_Standard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRestrurantHeader
    {
        public long intRestrurantId { get; set; }
        public string strRestrurantName { get; set; }
        public string strRestrurantType { get; set; }
        public bool IsActive { get; set; }
    }
}
