//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger_Industry_Standard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public long intUserID { get; set; }
        public long strUserType { get; set; }
        public long strUserName { get; set; }
        public bool IsActive { get; set; }
        public long intNgoID { get; set; }
        public string strUserMail { get; set; }
        public string strPassword { get; set; }
    }
}
